spring:
  application:
    name: flash ledger

  datasource:
    url: jdbc:mysql://localhost:3307/flashledger
    username: root
    password: root

# logging:
#   level:
#     org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener: OFF